[build]
  # Thư mục chứa ứng dụng để publish lên Netlify
  publish = "compact"
  
  # Ứng dụng này chỉ bao gồm HTML/CSS/JS tĩnh, không cần lệnh build
  command = ""

# Đảm bảo fallback route nếu có lỗi routing khi dùng URL (dành cho Single Page App) 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
